#
# version.cmake : version du projet
#

set (VTK_CONTRIB_MAJOR_VERSION "4")
set (VTK_CONTRIB_MINOR_VERSION "8")
set (VTK_CONTRIB_RELEASE_VERSION "4")
set (VTK_CONTRIB_VERSION ${VTK_CONTRIB_MAJOR_VERSION}.${VTK_CONTRIB_MINOR_VERSION}.${VTK_CONTRIB_RELEASE_VERSION})


