name: Spack CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call:
    name: Call Spack reusable workflow
    uses: LIHPC-Computational-Geometry/lihpccg-ci/.github/workflows/spack-reusable.yml@main
    with:
      test-link-options: "-DVTK_7:BOOL=ON -DUSE_OPENGL_BACKEND:BOOL=ON"